"""add inventory and advantage series

Revision ID: 2c733dcd0325
Revises: 6b969d7031a3
Create Date: 2026-07-31 22:35:01.966493

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2c733dcd0325'
down_revision: str | None = '6b969d7031a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('match_players', sa.Column('backpack', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('match_players', sa.Column('item_neutral', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('radiant_gold_adv', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('radiant_xp_adv', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'radiant_xp_adv')
    op.drop_column('matches', 'radiant_gold_adv')
    op.drop_column('match_players', 'item_neutral')
    op.drop_column('match_players', 'backpack')
    op.drop_column('match_players', 'items')
    op.drop_column('match_players', 'level')
    # ### end Alembic commands ###
