"""initial schema

Revision ID: 5b5824250f10
Revises: 
Create Date: 2026-07-31 21:35:21.229067

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5b5824250f10'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('game_mode', sa.Integer(), nullable=True),
    sa.Column('lobby_type', sa.Integer(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=True),
    sa.Column('patch', sa.Integer(), nullable=True),
    sa.Column('average_rank', sa.Integer(), nullable=True),
    sa.Column('detail_fetched', sa.Boolean(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_start_time'), 'matches', ['start_time'], unique=False)
    op.create_table('players',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('persona_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('rank_tier', sa.Integer(), nullable=True),
    sa.Column('estimate_mmr', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_match_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('match_players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('player_slot', sa.Integer(), nullable=False),
    sa.Column('is_radiant', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('lane_role', sa.Integer(), nullable=True),
    sa.Column('is_roaming', sa.Boolean(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('last_hits', sa.Integer(), nullable=True),
    sa.Column('denies', sa.Integer(), nullable=True),
    sa.Column('gold_per_min', sa.Integer(), nullable=True),
    sa.Column('xp_per_min', sa.Integer(), nullable=True),
    sa.Column('net_worth', sa.Integer(), nullable=True),
    sa.Column('hero_damage', sa.Integer(), nullable=True),
    sa.Column('tower_damage', sa.Integer(), nullable=True),
    sa.Column('hero_healing', sa.Integer(), nullable=True),
    sa.Column('obs_placed', sa.Integer(), nullable=True),
    sa.Column('sen_placed', sa.Integer(), nullable=True),
    sa.Column('camps_stacked', sa.Integer(), nullable=True),
    sa.Column('stuns_seconds', sa.Float(), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benchmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_slot', name='uq_match_players_slot')
    )
    op.create_index('ix_match_players_account_hero', 'match_players', ['account_id', 'hero_id'], unique=False)
    op.create_index(op.f('ix_match_players_account_id'), 'match_players', ['account_id'], unique=False)
    op.create_index(op.f('ix_match_players_hero_id'), 'match_players', ['hero_id'], unique=False)
    op.create_index(op.f('ix_match_players_match_id'), 'match_players', ['match_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_player_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_player_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_player_id', 'rule_key', name='uq_insights_rule')
    )
    op.create_index(op.f('ix_insights_match_player_id'), 'insights', ['match_player_id'], unique=False)
    op.create_index(op.f('ix_insights_rule_key'), 'insights', ['rule_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_rule_key'), table_name='insights')
    op.drop_index(op.f('ix_insights_match_player_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_match_players_match_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_hero_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_account_id'), table_name='match_players')
    op.drop_index('ix_match_players_account_hero', table_name='match_players')
    op.drop_table('match_players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_start_time'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
