"""add items cache

Revision ID: 6b969d7031a3
Revises: 51ef871472f0
Create Date: 2026-07-31 22:27:25.334788

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6b969d7031a3'
down_revision: str | None = '51ef871472f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('localized_name', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.create_index(op.f('ix_items_quality'), 'items', ['quality'], unique=False)
    op.create_index(op.f('ix_items_tier'), 'items', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_tier'), table_name='items')
    op.drop_index(op.f('ix_items_quality'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
