"""add parse extras: objectives, lane efficiency, parse job

Revision ID: e260d7fc7071
Revises: 2c733dcd0325
Create Date: 2026-07-31 22:52:47.924101

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e260d7fc7071'
down_revision: str | None = '2c733dcd0325'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('lane_efficiency_pct', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('teamfight_participation', sa.Float(), nullable=True))
    op.add_column('match_players', sa.Column('actions_per_min', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('neutral_kills', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('tower_kills', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('roshan_kills', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('buyback_count', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('pings', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('teamfight_count', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('first_blood_time', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('comeback', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('stomp', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('parse_job_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'parse_job_id')
    op.drop_column('matches', 'stomp')
    op.drop_column('matches', 'comeback')
    op.drop_column('matches', 'first_blood_time')
    op.drop_column('matches', 'teamfight_count')
    op.drop_column('matches', 'objectives')
    op.drop_column('match_players', 'pings')
    op.drop_column('match_players', 'buyback_count')
    op.drop_column('match_players', 'roshan_kills')
    op.drop_column('match_players', 'tower_kills')
    op.drop_column('match_players', 'neutral_kills')
    op.drop_column('match_players', 'actions_per_min')
    op.drop_column('match_players', 'teamfight_participation')
    op.drop_column('match_players', 'lane_efficiency_pct')
    # ### end Alembic commands ###
